name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            install: false
            start: npm run cypress:record
            browser: chrome
            record: true
            parallel: true
            group: 'E2E - Chrome'
            config: videosFolder=/tmp/cypress-videos 