name: Fake-Contact Test Cypress

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Reclaim cache directory
        run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome